desc NFO_BUSCALINHA;

select * from LINHA.LINHATELEFONICA
where DTULTIMAALTERACAO > sysdate - 10
AND IDTIPOLINHA=6
;

select IDLINHABASE,IDAREAREGISTRO,NRLINHA,DTULTIMAALTERACAO,IDESTADOLINHA, DTESTADOLINHA, IDNUMEROSISTEMAORIGEM, IDSISTEMAORIGEM from LINHABASE
where 
-- DTULTIMAALTERACAO > sysdate - 10 AND
NRLINHA >= 995752282
;

desc LINHABASE;

select * from TIPOLINHA;

