apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
   app: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxrc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 443
          - containerPort: 80
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
   worker_processes  1;
   events {
      worker_connections 1024;
   }

   http {
      proxy_cache_path  /var/cache/nginx/java-config levels=1:2 keys_zone=java-config:10m max_size=1g
                    inactive=310s use_temp_path=off;
      proxy_cache_path  /var/cache/nginx/oracle-query levels=1:2 keys_zone=oracle-query:10m max_size=1g
                    inactive=310s use_temp_path=off;
   
      server {

         listen 80;
      
         root /srv/http/java-config;
         index index.html index.htm;

         server_name localhost;

         location /java-config {
            add_header Cache-Control "no-cache, must-revalidate, max-age=0";
            add_header X-Proxy-Cache $upstream_cache_status;
         
            proxy_cache java-config;
            proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504 http_404;
            proxy_cache_lock on;
            proxy_cache_valid any 300s;
            proxy_ignore_headers X-Accel-Expires Expires Cache-Control;

            proxy_pass http://200.196.230.174:30088/r/java-hello/java-config;
            proxy_set_header Authorization "Basic VGhhbmsgeW91IGZvciByZWFkaW5nIGJuZWlqdC5ubAo=";
         }
      
         location /oracle-query {
            add_header Cache-Control "no-cache, must-revalidate, max-age=0";
            add_header X-Proxy-Cache $upstream_cache_status;
         
            proxy_cache oracle-query;
            proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504 http_404;
            proxy_cache_lock on;
            proxy_cache_valid any 300s;
            proxy_ignore_headers X-Accel-Expires Expires Cache-Control;

            proxy_pass http://200.196.230.174:30088/r/vivo-demo/vivo-ms-demo;
            proxy_set_header Authorization "Basic VGhhbmsgeW91IGZvciByZWFkaW5nIGJuZWlqdC5ubAo=";
         }
      }
   }